
name: Terraform Deploy

on:
  push:
    branches:
      - main

env:
  TF_VAR_aws_region: sa-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    
    env:
      TF_VAR_aws_region: sa-east-1
      TF_VAR_domain: ${{ secrets.DOMAIN }}
      TF_VAR_cloudflare_token: ${{ secrets.CLOUDFLARE_TOKEN }}
      TF_VAR_cloudflare_zone: ${{ secrets.CLOUDFLARE_ZONE }}
      TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS & Terraform
        uses: ./.github/actions/setup-env
        env:
          AWS_ROLE: arn:aws:iam::150457926438:role/website_actions
          AWS_REGION: ${{ env.TF_VAR_aws_region }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=anyenk-terraform-website" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=${{ env.TF_VAR_aws_region }}" \
            -backend-config="encrypt=true"

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
